<?php
global $CONFIGURA;


error_reporting(E_ERROR);


include __DIR__ . "/cactux3/fix_mysql_php7.php";
$path = str_replace($_SERVER['DOCUMENT_ROOT'], '', str_replace("\\","/",__DIR__));
$CACTUX_CONF['path'] = $path.'/';
// echo __DIR__;exit;

mysql_connect("127.0.0.1","root","");
mysql_select_db("frotafan");
mysql_set_charset('latin1');
ini_set( 'default_charset', 'latin1');

// VERIFICA SE DEVE CARREGAR UMA EMPRESA ESPECÕFICA OU A PADR√O
if ( $_GET[busca_empresa_configura] > 0 ) {
    $_POST[busca_empresa_configura] = $_GET[busca_empresa_configura];
}
if ($_POST[busca_empresa_configura] > 0) {
    $id_empresa = intval($_POST[busca_empresa_configura]);
} else {
    $id_empresa = 1;
}

$sql = mysql_query("SELECT * FROM empresa WHERE empr_nb_id = $id_empresa LIMIT 1");
$a = mysql_fetch_array($sql);

if ($a[empr_nb_cidade] > 0) {
    $sql_cida = mysql_query("SELECT * FROM cidade WHERE cida_nb_id = $a[empr_nb_cidade] LIMIT 1");
    $a_cida = mysql_fetch_array($sql_cida);

    $a_cida[cida_tx_nome] = strtr($a_cida[cida_tx_nome], "·ÈÌÛ˙‚ÍÙ„ı‡ËÏÚ˘Á", "¡…Õ”⁄¬ ‘√’¿»Ã“Ÿ«"); // O STRTOUPPERN√O COMVERTE PARA MAI⁄SCULO
    $a_cida[cida_tx_nome] = strtoupper(trim($a_cida[cida_tx_nome]));
}

$CONFIGURA[PATH] = $CACTUX_CONF['path'];
$CONFIGURA[MODULO] = 'kernel/';
$CONFIGURA[SPEDNFE] = '../spednfe/'; // USADO DENTRO DO KERNELS
$CONFIGURA[SPEDNFE_SISTEMA] = 'spednfe/'; // USADO DENTRO DO SISTEMA
$CONFIGURA[SPED_CACTUS] = '../../../sped_cactus/';
$CONFIGURA[LAYOUT] = 'layout';
$CONFIGURA[CONTROLE] = 'controle.php?arq=' . $CONFIGURA[MODULO];
$CONFIGURA[NOME_SISTEMA] = 'FROTA PLUS';
// $CONFIGURA[NOME_SISTEMA] = 'SISTEMA DE GEST√O FUNDI¡RIA';
$CONFIGURA[SISTEMA] = 'jessicamodachick';//USADO PARA IDENTIFICAR QUANDO O SISTEMA TEM ALGUMA CONFIGURA«√O ESPECÕFICA S” DELE

if (!empty($_SERVER['HTTPS'])) {//VERIFICA SE O HTTPS EST¡ ATIVO
    $CONFIGURA[HOST_SISTEMA] = 'https://'.$_SERVER[HTTP_HOST];
} else {
    $CONFIGURA[HOST_SISTEMA] = 'http://'.$_SERVER[HTTP_HOST];
}

$CONFIGURA[LINK_EXTERNO] = '';

$CONFIGURA[PASTA_NFE] = 'cactus';
$CONFIGURA[CLIENTE_NFE] = 'cactus';
$CONFIGURA[SERVIDOR_CACTUS] = "http://201.30.147.128/servidor_nfce/";
$CONFIGURA[AMBIENTE_NFE] = 2; // 1 - NORMAL; 2 - HOMOLOGA«√O
$CONFIGURA[SERIE] = 2;
$CONFIGURA[SERIE_MDFE] = 1;
$CONFIGURA[SERIE_CTE] = 1;
$CONFIGURA[BOTAO_COMPROVANTE] = 'SIM';
// $CONFIGURA[BOTAO_NFE] = 'SIM';
$CONFIGURA[BUSCA_PDV] = 'NOME|CODIGO|CODBARRAS|MARCA';
$CONFIGURA[NCM_OBRIBATORIO] = 'NAO'; // OBRIGA O NCM NO CADASTRO DE PRODUTO, PARA QUE NAO CONSIGA CADASTRAR

$CONFIGURA[CERTIFICADO] = $_SERVER[DOCUMENT_ROOT] . $CONFIGURA[PATH] . 'certificado/' . $a[empr_tx_certificado];
$CONFIGURA[SENHA] = $a[empr_tx_senhaCertificado];
$CONFIGURA[CSC] = $a[empr_tx_csc];
$CONFIGURA[CSCID] = $a[empr_tx_token];
$CONFIGURA[CNPJ] = preg_replace('/\D/', '', $a[empr_tx_cnpj]);
$CONFIGURA[UF] = $a_cida[cida_tx_uf];
$CONFIGURA[TIMEOUT] = 5;
$CONFIGURA[TOKEN_MULTIPLUS] = 'cactus000tef';
$CONFIGURA[COMUNICACAO_MULTIPLUS] = 'txt';
// $CONFIGURA[COMUNICACAO_MULTIPLUS] = 'webservice';

$CONFIGURA[NOME_IMPRESSAO] = utf8_encode(mb_strtoupper(strtr($a[empr_tx_razao], "·ÈÌÛ˙‚ÍÙ„ı‡ËÏÚ˘Á", "¡…Õ”⁄¬ ‘√’¿»Ã“Ÿ«")));
$CONFIGURA[CNPJ_IMPRESSAO] = 'CNPJ ' . $a[empr_tx_cnpj];
$CONFIGURA[ENDERECO_IMPRESSAO] = implode(', ', array_unique(array($a[empr_tx_endereco], $a[empr_tx_numero], $a[empr_tx_bairro])));
$CONFIGURA[CEP_IMPRESSAO] = $a_cida[cida_tx_nome] . ' - ' . $a_cida[cida_tx_uf] . ' - ' . $a[empr_tx_cep];
$CONFIGURA[COMPLEMENTO_IMPRESSAO] = $a[empr_tx_complemento];

if ( $a[empr_tx_fone]!='' && $a[empr_tx_cel]!='' ) {
    $tx_telefone = $a[empr_tx_fone].' / '.$a[empr_tx_cel];
} else {
    $tx_telefone = $a[empr_tx_fone].$a[empr_tx_cel];
}
$CONFIGURA[CONTATO_CABECALHO_PEDIDO] = 'Telefone: '.$tx_telefone.' <BR>E-mail: '.$a[empr_tx_email].' <BR><BR>';

$CONFIGURA[LARGURA_IMPRESSAO] = '80';
$CONFIGURA[ALTURA_IMPRESSAO] = '500';
$CONFIGURA[COPIA] = '1';

$CONFIGURA[IMPRESSAO_COMPROVANTE] = 'NAO'; // QUANDO SIM, IMPRIME O COMPROVANTE N√O FISCAL JUNTO COM A IMPRESS√O DO CUPOM FISCAL (NFCE)

$CONFIGURA[DESATIVA_COMPROVANTE_PDV] = 'NAO'; // QUANDO SIM, DESATIVA A IMPRESS√O DO COMPROVANTE N√O FISCAL DE VENDA NO PDV

$CONFIGURA[MARGEM_ESQUERDA] = '0';
$CONFIGURA[MARGEM_TOPO] = '0';
$CONFIGURA[MARGEM_DIREITA] = '0';

$CONFIGURA[PDF] = 'PDFVIEWER';
$CONFIGURA[BIOPDF] = 'C:\Program Files\bioPDF\PDF Writer\pdfcmd.exe ';
$CONFIGURA[SUMATRA] = 'C:\Program Files (x86)\SumatraPDF\SumatraPDF.exe';
// $CONFIGURA[PDFVIEWER] = 'C:\xampp\htdocs\kernel\impressao\PDFXCview.exe';
$CONFIGURA[PDFVIEWER] = $_SERVER['DOCUMENT_ROOT'].$CONFIGURA[PATH].$CONFIGURA[MODULO].'\impressao\PDFXCview.exe';
$CONFIGURA[IMPRESSORA] = 'MP-100S TH';
$CONFIGURA[IMPRESSORA_COZINHA] = 'MP-100S TH';
// $CONFIGURA[IMPRESSORA_ETIQUETA]='\\\\192.168.0.155\\Argox';
$CONFIGURA[IMPRESSORA_ETIQUETA] = 'ZDesigner GC420t (EPL)';
$CONFIGURA[IMPRESSORA_OFERTA] = 'MP-100S TH';
$CONFIGURA[POPUP] = 'SIM';// SE SIM, ABRE JANELA DE IMPRESSAO AO INVES DE IMPRIMIR DIRETO VIA CMD
// $CONFIGURA[MODO_IMPRESSAO] = 'WEBSOCKET';

$CONFIGURA[MODELO_ETIQUETA] = 'gera_pdf_etiqueta.php';
$CONFIGURA[MODELO_OFERTA] = 'gera_pdf_etiquetaOferta.php';

$CONFIGURA[VENDA_SEM_ESTOQUE] = 'SIM';

$CONFIGURA[EXIBE_SEM_ESTOQUE] = 'SIM';

$CONFIGURA[LABEL_USUARIO] = 'VENDEDOR';

$CONFIGURA[FECHAMENTO_CEGO] = 'SIM'; // PEQUENO BUG: SE "SIM", DESATIVA DO FECHAMENTO SEGO. SE "NAO", ATIVA O FECHAMENTO CEGO :)

//SE SIM REQUER AUTORIZACAO DO GERENTE AO EXCLUIR ITEM/PAGAMENTO NO PDV
$CONFIGURA[EXCLUIR_GERENTE] = 'NAO';

// SE SIM, BLOQUEIA A VENDA EM CARTEIRA CASO O CLIENTE N√O TENHA LIMITE DE CR…DITO
$CONFIGURA[LIMITE_CARTEIRA] = 'SIM';

// SE SIM, BLOQUEIA A VENDA EM BOLETO E DUPLICATA CASO O CLIENTE N√O TENHA LIMITE DE CR…DITO
$CONFIGURA[LIMITE_BOLETO_DUPLICATA] = 'SIM';

// ATIVA A PARTE DE COMISS’ES NO CADASTRO DE FUNCION¡RIOS
$CONFIGURA[COMISSAO_FUNCIONARIO] = 'SIM';



// SOLICITA A SENHA GERENCIAL/ADMINISTRATIVA PARA AUTORIZAR DESCONTO MAIOR QUE O VALOR PERMITIDO
$CONFIGURA[DESCONTO_SENHA_GERENCIAL] = 'SIM';

// PERMITE MODIFICAR O VALOR UNIT¡RIO DO PRODUTO
$CONFIGURA[MODIFICA_VALOR_UNITARIO] = 'NAO';

// GERA UM ALERTA NA TELA DE PEDIDO CASO O CLIENTE ESTEJA COM ALGUMA DÕVIDA EM ATRASO
$CONFIGURA[ALERTA_CLIENTE_EM_ATRASO] = 'SIM';
// BLOQUEA O PEDIDO DO CLIENTE INADIPL NTE E SOLICITA SENHA DE AUTOTIZA«√O
$CONFIGURA[BLOQUEIA_CLIENTE_EM_ATRASO] = 'SIM';

// PERMITE N√O ADICIONAR AS TAGS DE DUPLICATAS NA EMISS√O DE NFE
$CONFIGURA[OCULTA_DUPLICATAS_NFE] = 'SIM';


// BLOQUEIA A BUSCA PELO NOME DO PRODUTO NO PDV
// $CONFIGURA[BLOQUEIA_BUSCA_NOME_PDV]='SIM';

//CONFIGURA COMBONET DOS PRODUTOS NO ARQUIVO PDV.PHP NA FUNCAO NOME_PRODUTO
//FLANDPE«AS = ADICIONA AS MARCAS DOS PRODUTOS NA BUSCA E NO GRID
// $CONFIGURA[MODO_PDV]='FLANDPE«AS';

//ADICIONA AO MENU O MODULO DE ORDEM DE SERVICO
// $CONFIGURA[ORDEM_SERVICO]='SIM';

//CONFIGURA A CATEGORIA DE SERVI«OS PARA EXIBICAO DE DETALHES PDV E GERACAO FISCAL
// $CONFIGURA[CATEGORIA_SERVICO] = '50';


// QUANDO IGUAL A "SIM", O SISTEMA PERMITE VENDAR POR SETORES DIFERENTES DO SETOR DE ID 1. QUANDO DIFERENTE DE "SIM", O SISTEMA VAI FAZER O CONTROLE DE ESTOQUE DA VENDA DIRETAMENTE NO SETOR DE ID 1
$CONFIGURA[VENDA_POR_SETOR] = 'NAO';




$CONFIGURA[MODO_FROTAS]      = 'SIM';

$CONFIGURA[MODO_OFICINA]     = 'NAO';

$CONFIGURA[MODO_RESTAURANTE] = 'SIM';

$CONFIGURA[MODO_ASSISTENCIA] = 'SIM';

$CONFIGURA[MODO_TRANSPORTADORA] = 'SIM';

$CONFIGURA[MODO_ALMOXARIFADO] = 'NAO';

$CONFIGURA[MODO_PRODUCAO] = 'SIM';

$CONFIGURA[MODO_MANUFATURA] = 'SIM';

$CONFIGURA[MODO_VENDAS] = 'SIM';



$CONFIGURA[USA_BALANCA] = 'NAO';


$CONFIGURA[EXCLUIR_RECEITAS] = 'SIM';



// PERMITE DESABILITAR A IDENTIFICA«√O AUTOMATICA DA PLACA DO VEICULO DO CLIENTE
$CONFIGURA[SELECAO_AUTOMATICA_PLACA] = 'NAO';


// SE SIM, NO PROCESSO DE PEDIDOS, EXIBE UM MODAL AO CLICAR NO BOT√O DE ENVIAR PARA O PDV PARA ESCOLHER QUAL FORMA DE PAGAMENTO O CLIENTE ESCOLHEU
$CONFIGURA[NEGOCIAR_FORMA_PAGAMENTO_PDV] = 'NAO';



// PERMITE DEFINIR OS VALORES PADR’ES NO PROCESSO DE REQUISI«√O DE COMPRAS
$CONFIGURA[REQUISICAO_COMPRA_CENTROCUSTO] = 1;
$CONFIGURA[REQUISICAO_COMPRA_PLANOCONTA]  = 1;

$CONFIGURA[QTDE_PARCELAS_FATURAMENTO_PEDIDO] = 12;

// PERMITE ENVIAR DE FORMA AUTOM¡TICA, O XML E PDF DA NOTA FISCAL PARA O EMAIL DO CLIENTE AO AUTORIZAR A NOTA
$CONFIGURA[ENVIO_AUTOMATICO_EMAIL_NFE]  = 'NAO';
$CONFIGURA[ENVIO_AUTOMATICO_EMAIL_NFCE] = 'NAO';

// PERMITE CONFIGURAR UM EMAIL PARA SEMPRE RECEBER UMA C”PIA DO EMAIL ENVIADO PARA O CLIENTE
$CONFIGURA[COPIA_ENVIO_AUTOMATICO_EMAIL] = '';


$CONFIGURA[PERMISSAO_VENDA] = 'Vendedor';

// // PERMITE IDENTIFICAR QUAIS IDS S√O BOLETO E DUPLICATA NO SISTEMA. ISSO … ⁄TIL PARA SISTEMAS ANTIGOS EM QUE O ID N√O … O MESMO DO VENDAS PADR√O
// $CONFIGURA[ID_BOLETO]    = '';
// $CONFIGURA[ID_DUPLICATA] = '';


// EXIBE UM BOT√O DE IMPRIMIR NA TELA DE FINALIZA«√O DE PEDIDO DO PDV
$CONFIGURA[BOTAO_IMPRIMIR_PEDIDO_FINALIZAR_PDV] = '';


// QUANDO "SIM", NA TELA DE PEDIDO N√O EXIBE O BOT√O "PDV" SENDO ESTE TRANSFERIDO PARA A TELA DE FATURAMENTO, ONDE ESTA IR¡ GERAR O FINANCEIRO SEM FINALIZAR E FAZER O ENVIO PARA O PDV. CONFIGURA«√O CRIADA PARA A TD ATACADO
$CONFIGURA[FINALIZAR_FINANCEIRO_PEDIDO_NO_PDV] = 'NAO';


// SERVE PARA IDENTIFICAR QUAL O ID DO SERVI«O DA TAXA DE ENTREGA
$CONFIGURA[ID_PRODUTO_SERVICO_DELIVERY] = 12058;



// PERMITE UMA QTDE DE DIAS PADR√O PARA FILTRAR AO ABRIR A TELA DE EMISS√O (SERVE PARA CASOS ONDE O SISTEMA DO CLIENTE ESTIVER MUITO LENTO)
$CONFIGURA[NFE_LIMITE_FILTRO_INICIAL] = '';
$CONFIGURA[NFCE_LIMITE_FILTRO_INICIAL] = '';


// DADOS DA API UTILIZADA PARA FAZER CONSULTA NA FERRAMENTA DE BUSCA DE NOTAS DA CACTUS
$CONFIGURA['API_CONSULTA_XML_CACTUS'] = [
    'ENDPOINT' => 'https://sistemascactus.com/consulta_xml_cactus/',
    'CONSULTA_CHAVE' => 'consulta_chave.php',
    'NFE_EMPRESA' => 'nfe_empresa.php',
];



$EMAIL['GERAL'] = [
    'AUTENTICACAO_SMTP' => true,
    'HOST'              => 'in-v3.mailjet.com',
    'PORTA'             => 587,
    'USUARIO'           => 'aaffc202889879240ff553c5ca95d178',
    'SENHA'             => '8b7d9afb84bb11bbddcb14130afc76e0',
    // 'USUARIO'           => '17d689632368118d52433f09245aa1ac',
    // 'SENHA'             => 'ae6dee6b0edf788f62b28a8678e5f00d',
    'ENVIAR_DE'         => 'sistemas@cactustecnologia.com.br',
    'NOME_REMETENTE'    => $CONFIGURA['NOME_IMPRESSAO'],
    'RESPONDER_PARA'    => 'nao-responder@cactustecnologia.com.br',
];


// AQUI PODE SER FEITA A CONFIGURA«√O DE UMA CONTA PARA UM SETOR ESPECÕFICA
$EMAIL['ENVIO_PEDIDOS'] = $EMAIL['GERAL'];
$EMAIL['ENVIO_FISCAL'] = $EMAIL['GERAL'];
$EMAIL['ENVIO_AZAPFY'] = $EMAIL['GERAL'];



//MUDA O LABEL DE VENDEDOR PARA PRESCRITOR
// $CONFIGURA[MODO_PRESCRITOR]='SIM';

//MUDA O SISTEMA BASE
// $CONFIGURA[SISTEMA]='QUALIVITA';

// $CONFIGURA[TAXA_ENTREGA]='0';

//CONFIGURACAO DE IMPRESSAO

//POPUP = ABRE JANELA DE IMPRESSAO AO INVES DE IMPRIMIR DIRETO VIA CMD
// $CONFIGURA[MODO_IMPRESSAO]='POPUP';

