export * from './brandData'
export * from './sliderDetails'
export * from './reviewScreen'
export * from './keyFeatures'
export * from './infoContainer'
export * from './iconProduct'
export * from './detailsText'
export * from './descriptionText'
