export type RootStackParamList = {
  Splash: undefined
  OnBoarding: undefined
  OnboardingTwo: undefined
  Login: undefined
  ForgetPassword: undefined
  SignUp: undefined
  OtpVerfication: undefined
  ResetPassword: undefined
  CategoryDetail: undefined
  LoaderScreen: undefined
  DrawerScreen: undefined
  NotificationScreen: undefined
  NotificationContainer: undefined
  MyWhishList: undefined
  WhishlitContainer: undefined
  EditProfile: undefined
  OrderHistory: undefined
  HomeScreenTwo: undefined
  OfferScreen: undefined
  Settings: undefined
  PaymentScreen: undefined
  ChangePasswordScreen: undefined
  AddressScreen: undefined
  AddtocartOne: undefined
  AddToCartTwo: undefined
  ChangeAddressScreen: undefined
  CheckoutScreen: undefined
  ProductDetailOne: undefined
  RatingScreen: undefined
  CategoryTwo: undefined
  VoucherScreen: undefined
  ProductDetailTwo: undefined
  OrderStatus: undefined
  ProductDetailThree: undefined
  CategoryScreen: undefined
  PageListScreen: undefined
}
